from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_openrouter import ChatOpenRouter 

load_dotenv()

llm = ChatOpenRouter(
    model= "openai/gpt-oss-20b:free",
    temperature=0,
    # other params...
)

def main():
    print("Hello from langchain-course!")
    information = """
YouTube is an American online video-sharing platform owned by Google. YouTube was founded on February 14, 2005, by Chad Hurley, Jawed Karim, and Steve Chen who were all former employees at PayPal.[7] Headquartered in San Bruno, California, it is the second-most-visited website in the world, after Google itself. In January 2024, YouTube had reached more than 2.7 billion monthly active users, who collectively watched more than one billion hours of video every day.[8] As of May 2019, videos were being uploaded to the platform at a rate of more than 500 hours of video per minute,[9][10] and as of mid-2024, there were approximately 14.8 billion videos in total.[11]

On November 13, 2006, YouTube was purchased by Google for 1.65 billion USD (equivalent to $2.44 billion in 2025).[12] Google expanded YouTube's business model from generating revenue through advertisements alone to paid offerings such as movies and exclusive programming explicitly produced for YouTube. It also offers YouTube Premium, a paid subscription option for watching videos without ads. YouTube incorporated the Google AdSense program, generating more revenue for both YouTube and approved users. In 2023, YouTube's advertising revenue totaled $31.7 billion, a 2% increase from the $31.1 billion reported in 2022.[13] From Q4 2023 to Q3 2024, YouTube's combined revenue from advertising and subscriptions exceeded $50 billion.[14]

Since its purchase by Google, YouTube has expanded beyond the core website, creating mobile apps, network television, games, and the ability to link with other platforms. Video categories on YouTube include music videos, video clips, news, short and feature films, songs, documentaries, movie trailers, teasers, TV spots, live streams, vlogs, and more. Most submissions are generated by individuals, including collaborations between YouTubers and corporate sponsors. Established media, news, and entertainment corporations have also created and expanded their visibility on YouTube channels to reach bigger audiences.

YouTube has had unprecedented social impact, influencing popular culture, internet trends, and creating multimillionaire celebrities. Despite its growth and success, the platform has been criticized for its facilitation of the spread of misinformation and copyrighted material, routinely violating its users' privacy, excessive censorship, endangering the safety of children and their well-being, and for its inconsistent implementation of platform guidelines.
    """

    summary_template = """
    given the information {information} about a thing, I want you to create:
    1. A short summary 
    2. Two interesting facts about it
    """

    summary_prompt_template = PromptTemplate(
        input_variables=["information"],
        template=summary_template
    )

    chain = summary_prompt_template | llm
    response = chain.invoke({"information": information})
    print(response.content)

if __name__ == "__main__":
    main()
